baseurl = "/"
languageCode = "en-us"
title = "Rich Mountain Cabin"
theme = "hugo-theme-casper"
#disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-140858717-1"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Nick Haskins"
  authorlocation = "Boone, NC"
  authorwebsite = "https://richmountaincabin.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-140858717-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "nphaskins"
  #twitterName = "nphaskins"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
